# Generated by Django 5.2.5 on 2025-08-14 15:46

import django.core.validators
import django.db.models.deletion
import hauptverwalter.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Legislatur',
            fields=[
                ('nummer', models.IntegerField(help_text='Nummer Legislaturperiode', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('anfangsdatum', models.DateField(help_text='Wann beginnt die Legislaturperiode?')),
                ('enddatum', models.DateField(help_text='Wann endet die Legislaturperiode?')),
            ],
        ),
        migrations.CreateModel(
            name='Antrag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nummer', models.IntegerField(editable=False, help_text='Nummer des Antrags in der Legislatur', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('titel', models.CharField(help_text='Antragstitel', max_length=300)),
                ('typ', models.CharField(choices=[('F', 'Finanzantrag'), ('S', 'Satzungs- oder Ordnungsänderungsantrag'), ('P', 'Positionierungsantrag'), ('A', 'Antrag')], default='A', max_length=1)),
                ('text', models.TextField(help_text='Antragstext', max_length=20000)),
                ('begruendung', models.TextField(help_text='Begründung des Antrags', max_length=40000)),
                ('minlesungen', models.IntegerField(help_text='Minimal nötige Lesungen bis zur Abstimmung', validators=[django.core.validators.MinValueValidator(1)])),
                ('antragssumme', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('haushaltsposten', models.CharField(blank=True, help_text='Aus welchem Haushaltsposten wird Geld beantragt (nur Kennummer)?', max_length=10, null=True)),
                ('orgsatzungsaenderung', models.BooleanField(blank=True, default=False, help_text='Geht es um eine Änderung der Organisationssatzung?')),
                ('synopse', models.FileField(blank=True, help_text='Synopse bei Änderung von Ordnungen oder Satzungen', null=True, upload_to=hauptverwalter.models.makeuploadpatsynopse)),
                ('anhang', models.FileField(blank=True, help_text='Anhang an den Antrag', null=True, upload_to=hauptverwalter.models.makeuploadpathanhang)),
                ('antragssteller', models.CharField(help_text='Antragssteller:innen (Name, HSG, Gremium...)', max_length=500)),
                ('kontaktemail', models.EmailField(help_text='Emailadresse für automatische Updates und Nachfragen', max_length=254)),
                ('kontaktperson', models.CharField(blank=True, help_text='Eine spezifische Kontaktperson für Nachfragen', max_length=100)),
                ('status', models.CharField(choices=[('B', 'In Beratung'), ('A', 'Angenommen'), ('N', 'Abgelehnt'), ('Z', 'Zurückgezogen'), ('X', 'Nicht behandelt'), ('P', 'Vom Präsidium zurückgewiesen')], default='B', max_length=1)),
                ('system_eingereicht', models.DateTimeField(auto_now_add=True)),
                ('formell_eingereicht', models.DateTimeField(help_text='Formelles Einreichdatum für Priorisierung, Fristen etc')),
                ('legislatur', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='hauptverwalter.legislatur')),
            ],
        ),
        migrations.CreateModel(
            name='Sitzung',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nummer', models.IntegerField(blank=True, help_text='Nummer der Sitzung', null=True, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('anfang', models.DateTimeField(help_text='Wann beginnt die Sitzung?')),
                ('ende', models.DateTimeField(blank=True, help_text='Wann endet(e) die Sitzung?', null=True)),
                ('sondersitzung', models.BooleanField(blank=True, help_text='Ist die Sitzung eine Sondersitzung?')),
                ('anmerkungen', models.TextField(blank=True, max_length=1000, null=True)),
                ('ort', models.CharField(max_length=1000)),
                ('legislatur', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='hauptverwalter.legislatur')),
            ],
            options={
                'ordering': ['-legislatur__nummer', '-nummer'],
            },
        ),
        migrations.CreateModel(
            name='Lesung',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('protokolleintraege', models.TextField(blank=True, help_text='Protokolleinträge zur Lesung, z.B. Diskussionsnotizen, GO-Anträge', max_length=50000)),
                ('abstimmbar', models.BooleanField(blank=True, default=False, editable=False, help_text='Kann bei dieser Lesung planmäßig abgestimmt werden?', null=True)),
                ('dringlichkeit_beantragt', models.BooleanField(blank=True, default=False, help_text='Könnte in dieser Lesung abgestimmt werden, wenn ein Dringlichkeitsantrag angeommen wird?', null=True)),
                ('status', models.CharField(choices=[('AV', 'Softwarevorschlag'), ('NN', 'Noch nicht gelesen'), ('E', 'Erfolgreich gelesen'), ('V', 'Manuell Vertagt'), ('ZV', 'Wegen Ende der Sitzung vertagt'), ('B', 'Wegen Beschlussunfähigkeit vertagt'), ('A', 'Abgestimmt'), ('T', 'Schwebende Lesung / als Tischvorlage')], default='NN', help_text='In Welchem Status ist die Lesung', max_length=2)),
                ('antrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hauptverwalter.antrag')),
                ('sitzung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hauptverwalter.sitzung')),
            ],
            options={
                'ordering': ['antrag__legislatur__nummer', 'antrag__nummer', 'sitzung__nummer'],
            },
        ),
        migrations.CreateModel(
            name='Unterantrag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nummer', models.IntegerField(editable=False, help_text='Nummer des Subantrags', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('titel', models.CharField(help_text='Antragstitel', max_length=300)),
                ('text', models.TextField(help_text='Antragstext', max_length=20000)),
                ('begruendung', models.TextField(help_text='Begründung des Antrags', max_length=40000)),
                ('antragssteller', models.CharField(help_text='Antragssteller:innen (Name, HSG, Gremium...)', max_length=500)),
                ('kontaktemail', models.EmailField(help_text='Emailadresse für automatische Updates und Nachfragen', max_length=254)),
                ('kontaktperson', models.CharField(blank=True, help_text='Eine spezifische Kontaktperson für Nachfragen', max_length=100)),
                ('status', models.CharField(choices=[('B', 'In Beratung'), ('A', 'Angenommen'), ('N', 'Abgelehnt'), ('Z', 'Zurückgezogen'), ('X', 'Nicht behandelt'), ('P', 'Vom Präsidium zurückgewiesen')], default='B', max_length=1)),
                ('system_eingereicht', models.DateTimeField(auto_now_add=True)),
                ('formell_eingereicht', models.DateTimeField(auto_now_add=True)),
                ('anhang', models.FileField(blank=True, help_text='Anhang an den Änderungsantrag', null=True, upload_to=hauptverwalter.models.makeuploadpathanhang)),
                ('hauptantrag', models.ForeignKey(limit_choices_to={'status': 'B'}, on_delete=django.db.models.deletion.CASCADE, to='hauptverwalter.antrag')),
            ],
            options={
                'ordering': ['hauptantrag__legislatur__nummer', 'hauptantrag__nummer', 'nummer'],
            },
        ),
        migrations.AddConstraint(
            model_name='antrag',
            constraint=models.UniqueConstraint(fields=('legislatur', 'nummer'), name='unique_legislatur_nummer_antrag'),
        ),
        migrations.AlterUniqueTogether(
            name='lesung',
            unique_together={('antrag', 'sitzung')},
        ),
        migrations.AddConstraint(
            model_name='unterantrag',
            constraint=models.UniqueConstraint(fields=('hauptantrag', 'nummer'), name='unique_hauptantrag_nummer_unterantrag'),
        ),
    ]
