# Generated by Django 5.2.5 on 2025-08-12 13:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Legislatur',
            fields=[
                ('nummer', models.IntegerField(help_text='Nummer Legislaturperiode', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('anfangsdatum', models.DateField(help_text='Wann beginnt die Legislaturperiode?')),
                ('enddatum', models.DateField(help_text='Wann endet die Legislaturperiode?')),
            ],
        ),
        migrations.CreateModel(
            name='Antrag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nummer', models.IntegerField(editable=False, help_text='Nummer des Antrags in der Legislatur', validators=[django.core.validators.MinValueValidator(1)])),
                ('titel', models.CharField(help_text='Antragstitel', max_length=300)),
                ('text', models.TextField(help_text='Antragstext', max_length=20000)),
                ('begruendung', models.TextField(help_text='Begründung des Antrags', max_length=40000)),
                ('minlesungen', models.IntegerField(help_text='Minimal nötige Lesungen bis zur Abstimmung', validators=[django.core.validators.MinValueValidator(1)])),
                ('antragssumme', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('antragssteller', models.CharField(help_text='Antragssteller:innen (Name, HSG, Gremium...)', max_length=500)),
                ('kontaktemail', models.EmailField(help_text='Emailadresse für automatische Updates', max_length=254)),
                ('status', models.CharField(choices=[('B', 'In beratung'), ('A', 'Angenommen'), ('N', 'Abgelehnt'), ('Z', 'Zurückgezogen'), ('X', 'Nicht behandelt')], max_length=1)),
                ('system_eingereicht', models.DateTimeField(auto_now_add=True, help_text='Antrag im System eingereicht')),
                ('formell_eingereicht', models.DateTimeField(auto_now_add=True, help_text='Formelles Einreichdatum für Priorisierung, Fristen etc')),
                ('legislatur', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='hauptverwalter.legislatur')),
            ],
        ),
        migrations.CreateModel(
            name='Sitzung',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nummer', models.IntegerField(editable=False, help_text='Nummer der Sitzung', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('anfang', models.DateTimeField(help_text='Wann beginnt die Sitzung?', unique_for_date=True)),
                ('ende', models.DateTimeField(blank=True, help_text='Wann endete die Sitzung?', null=True)),
                ('sondersitzung', models.BooleanField(blank=True, help_text='Ist die Sitzung eine Sondersitzung?')),
                ('anmerkungen', models.TextField(blank=True, max_length=1000, null=True)),
                ('ort', models.CharField(max_length=1000)),
                ('legislatur', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='hauptverwalter.legislatur')),
            ],
        ),
        migrations.CreateModel(
            name='Unterantrag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nummer', models.IntegerField(editable=False, help_text='Nummer des Subantrags', validators=[django.core.validators.MinValueValidator(1)])),
                ('titel', models.CharField(help_text='Antragstitel', max_length=300)),
                ('text', models.TextField(help_text='Antragstext', max_length=20000)),
                ('begruendung', models.TextField(help_text='Begründung des Antrags', max_length=40000)),
                ('antragssteller', models.CharField(help_text='Antragssteller:innen (Name, HSG, Gremium...)', max_length=500)),
                ('kontaktemail', models.EmailField(help_text='Emailadresse für automatische Updates', max_length=254)),
                ('status', models.CharField(choices=[('B', 'In beratung'), ('A', 'Angenommen'), ('N', 'Abgelehnt'), ('Z', 'Zurückgezogen'), ('X', 'Nicht behandelt')], max_length=1)),
                ('system_eingereicht', models.DateTimeField(auto_now_add=True, help_text='Antrag im System eingereicht')),
                ('formell_eingereicht', models.DateTimeField(auto_now_add=True, help_text='Formelles Einreichdatum für Priorisierung, Fristen etc')),
                ('hauptantrag', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='hauptverwalter.antrag')),
            ],
        ),
    ]
