# Generated by Django 5.2.5 on 2026-06-30 14:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vorlage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titel', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=20000)),
                ('zeigen', models.BooleanField(default=True, help_text='Soll die Vorlage sichtbar sein?')),
                ('eingereicht_technisch', models.DateTimeField(auto_now_add=True)),
                ('eingereicht_organisatorisch', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Faden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('kontaktperson', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Legislatur',
            fields=[
                ('nummer', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('anfang', models.DateField()),
                ('ende', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sitzung',
            fields=[
                ('nummer', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('anfang', models.DateTimeField()),
                ('ende', models.DateTimeField(blank=True, null=True)),
                ('ort', models.CharField(max_length=255)),
                ('legislatur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitzungen', to='hauptverwalter.legislatur')),
                ('protokoll_beschlossen_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beschlossene_protokolle', to='hauptverwalter.sitzung')),
            ],
        ),
        migrations.CreateModel(
            name='Tagesordnungspunkt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('protokolltext', models.TextField(blank=True, max_length=10000, null=True)),
                ('nummer', models.IntegerField(blank=True, help_text='Die Nummer dieses TOPs in der Tagesordnung der Sitzung', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('ergebnis', models.CharField(blank=True, choices=[('E', 'Erfolgreich behandelt'), ('X', 'Manuell vertagt'), ('U', 'Durch Sitzungsende vertagt'), ('A', 'Abgestimmt/Entschieden')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Antrag',
            fields=[
                ('vorlage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hauptverwalter.vorlage')),
                ('begruendung', models.TextField(max_length=40000)),
                ('antragssteller', models.CharField(max_length=500)),
            ],
            bases=('hauptverwalter.vorlage',),
        ),
        migrations.AddField(
            model_name='vorlage',
            name='faden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vorlagen', to='hauptverwalter.faden'),
        ),
        migrations.AddField(
            model_name='faden',
            name='aktuelle_vorlage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faden_aktuell', to='hauptverwalter.vorlage'),
        ),
        migrations.AddField(
            model_name='faden',
            name='ueberfaden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unterfaeden', to='hauptverwalter.faden'),
        ),
        migrations.CreateModel(
            name='Anhang',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datei', models.FileField(upload_to='anhang/')),
                ('titel', models.CharField(max_length=255)),
                ('hochgeladen_am', models.DateTimeField(auto_now_add=True)),
                ('zeigen', models.BooleanField(default=True, help_text='Soll der Anhang sichtbar sein?')),
                ('faden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anhaenge', to='hauptverwalter.faden')),
            ],
        ),
        migrations.CreateModel(
            name='Schiffchen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('erwartete_lesungen', models.IntegerField(help_text='Wie viele Lesungen werden für diesen Antrag erwartet? (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('hauptfaden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schiffchen', to='hauptverwalter.faden')),
                ('legislatur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schiffchen', to='hauptverwalter.legislatur')),
            ],
        ),
        migrations.CreateModel(
            name='Lesung',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dringlichkeit_beantragt', models.BooleanField(default=False, help_text='Könnte in dieser Lesung abgestimmt werden, wenn ein Dringlichkeitsantrag angenommen wird?')),
                ('schiffchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesungen', to='hauptverwalter.schiffchen')),
            ],
        ),
        migrations.CreateModel(
            name='Sondersitzung',
            fields=[
                ('sitzung_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hauptverwalter.sitzung')),
                ('anmerkung', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            bases=('hauptverwalter.sitzung',),
        ),
        migrations.CreateModel(
            name='Tischvorlage',
            fields=[
                ('tagesordnungspunkt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hauptverwalter.tagesordnungspunkt')),
                ('begruendung', models.TextField(blank=True, max_length=40000, null=True)),
                ('angenommen', models.BooleanField(default=False)),
            ],
            bases=('hauptverwalter.tagesordnungspunkt',),
        ),
        migrations.AddField(
            model_name='tagesordnungspunkt',
            name='lesung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagesordnungspunkte', to='hauptverwalter.lesung'),
        ),
        migrations.AddField(
            model_name='tagesordnungspunkt',
            name='sitzung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagesordnungspunkte', to='hauptverwalter.sitzung'),
        ),
        migrations.CreateModel(
            name='Finanzantrag',
            fields=[
                ('antrag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hauptverwalter.antrag')),
                ('antragssumme', models.DecimalField(decimal_places=2, max_digits=20)),
                ('haushaltsposten', models.CharField(help_text='Aus welchem Haushaltsposten wird Geld beantragt (nur Kennummer)?', max_length=10)),
            ],
            bases=('hauptverwalter.antrag',),
        ),
        migrations.CreateModel(
            name='SOAntrag',
            fields=[
                ('antrag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hauptverwalter.antrag')),
                ('orgsatzungsaenderung', models.BooleanField(blank=True, default=False, help_text='Geht es um eine Änderung der Organisationssatzung?', null=True)),
            ],
            bases=('hauptverwalter.antrag',),
        ),
        migrations.AlterUniqueTogether(
            name='tagesordnungspunkt',
            unique_together={('sitzung', 'nummer')},
        ),
    ]
