# Generated by Django 5.2.5 on 2026-07-02 16:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hauptverwalter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagesordnungspunkt',
            name='manueller_titel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitzung',
            name='nummer',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tagesordnungspunkt',
            name='lesung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagesordnungspunkte', to='hauptverwalter.lesung'),
        ),
    ]
