# Generated by Django 5.2.5 on 2025-10-09 13:39

import hauptverwalter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hauptverwalter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unterantrag',
            name='synopse',
            field=models.FileField(blank=True, help_text='Synopse bei Änderung von Ordnungen oder Satzungen (falls relevant)', null=True, upload_to=hauptverwalter.models.makeuploadpatsynopse),
        ),
        migrations.AlterField(
            model_name='antrag',
            name='anhang',
            field=models.FileField(blank=True, help_text='Anhang an den Antrag / Unterantrag', null=True, upload_to=hauptverwalter.models.makeuploadpathanhang),
        ),
        migrations.AlterField(
            model_name='antrag',
            name='formell_eingereicht',
            field=models.DateTimeField(auto_now_add=True, help_text='Formelles Einreichdatum für Priorisierung, Fristen etc'),
        ),
        migrations.AlterField(
            model_name='antrag',
            name='synopse',
            field=models.FileField(blank=True, help_text='Synopse bei Änderung von Ordnungen oder Satzungen (falls relevant)', null=True, upload_to=hauptverwalter.models.makeuploadpatsynopse),
        ),
        migrations.AlterField(
            model_name='unterantrag',
            name='anhang',
            field=models.FileField(blank=True, help_text='Anhang an den Antrag / Unterantrag', null=True, upload_to=hauptverwalter.models.makeuploadpathanhang),
        ),
        migrations.AlterField(
            model_name='unterantrag',
            name='formell_eingereicht',
            field=models.DateTimeField(auto_now_add=True, help_text='Formelles Einreichdatum für Priorisierung, Fristen etc'),
        ),
    ]
