# Generated by Django 5.2.5 on 2025-08-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hauptverwalter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitzung',
            name='anfang',
            field=models.DateTimeField(help_text='Wann beginnt die Sitzung?'),
        ),
    ]
