# Generated by Django 5.2.5 on 2025-08-12 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hauptverwalter', '0002_alter_sitzung_anfang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitzung',
            name='anfang',
            field=models.DateTimeField(help_text='Wann beginnt die Sitzung?', unique_for_date=True),
        ),
        migrations.AlterField(
            model_name='sitzung',
            name='nummer',
            field=models.IntegerField(editable=False, help_text='Nummer der Sitzung', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddConstraint(
            model_name='sitzung',
            constraint=models.UniqueConstraint(fields=('legislatur', 'nummer'), name='unique_legislatur_nummer_sitzung'),
        ),
    ]
