# Generated by Django 5.2.5 on 2025-10-09 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hauptverwalter', '0002_unterantrag_synopse_alter_antrag_anhang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesung',
            name='prio',
            field=models.IntegerField(blank=True, help_text='Niedrige Werte tauchen auf generierten Tagesordnungen früher auf', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Priorität'),
        ),
        migrations.AlterField(
            model_name='antrag',
            name='antragssumme',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
