# Generated by Django 5.2.5 on 2026-07-07 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hauptverwalter', '0002_tagesordnungspunkt_manueller_titel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesung',
            name='dringlichkeit_beantragt',
        ),
    ]
