# Generated by Django 5.2.5 on 2025-08-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hauptverwalter', '0003_alter_sitzung_anfang_alter_sitzung_nummer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitzung',
            name='anfang',
            field=models.DateTimeField(help_text='Wann beginnt die Sitzung?'),
        ),
    ]
