# Generated by Django 5.2.5 on 2026-07-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hauptverwalter', '0003_remove_lesung_dringlichkeit_beantragt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anhang',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vorlage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
