# Generated by Django 5.2.5 on 2025-11-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hauptverwalter', '0003_lesung_prio_alter_antrag_antragssumme'),
    ]

    operations = [
        migrations.AddField(
            model_name='antrag',
            name='anmerkungen_extern',
            field=models.TextField(blank=True, help_text='Von außen lesbare Anmerkungen des Präsidiums', max_length=10000),
        ),
        migrations.AddField(
            model_name='antrag',
            name='anmerkungen_intern',
            field=models.TextField(blank=True, help_text='Von außen _nicht_ lesbare Anmerkungen des Präsidiums', max_length=10000),
        ),
        migrations.AddField(
            model_name='unterantrag',
            name='anmerkungen_extern',
            field=models.TextField(blank=True, help_text='Von außen lesbare Anmerkungen des Präsidiums', max_length=10000),
        ),
        migrations.AddField(
            model_name='unterantrag',
            name='anmerkungen_intern',
            field=models.TextField(blank=True, help_text='Von außen _nicht_ lesbare Anmerkungen des Präsidiums', max_length=10000),
        ),
        migrations.AlterField(
            model_name='antrag',
            name='antragssteller',
            field=models.CharField(help_text='Formelle Antragssteller:innen (Name, HSG, Gremium...)', max_length=500),
        ),
        migrations.AlterField(
            model_name='antrag',
            name='kontaktemail',
            field=models.EmailField(help_text='Emailadresse für automatische Updates und Nachfragen, wird nicht veröffentlicht', max_length=254),
        ),
        migrations.AlterField(
            model_name='antrag',
            name='kontaktperson',
            field=models.CharField(blank=True, help_text='Eine spezifische Kontaktperson für Nachfragen, wird nicht veröffentlicht', max_length=100),
        ),
        migrations.AlterField(
            model_name='lesung',
            name='status',
            field=models.CharField(choices=[('AV', 'Softwarevorschlag'), ('NN', 'Noch nicht gelesen'), ('E', 'Erfolgreich gelesen'), ('V', 'Manuell Vertagt'), ('ZV', 'Wegen Ende der Sitzung vertagt'), ('B', 'Wegen Beschlussunfähigkeit vertagt'), ('A', 'Abgestimmt'), ('T', 'Schwebende Lesung / als Tischvorlage'), ('NT', 'Aufname nach ')], default='NN', help_text='In Welchem Status ist die Lesung', max_length=2),
        ),
        migrations.AlterField(
            model_name='unterantrag',
            name='antragssteller',
            field=models.CharField(help_text='Formelle Antragssteller:innen (Name, HSG, Gremium...)', max_length=500),
        ),
        migrations.AlterField(
            model_name='unterantrag',
            name='kontaktemail',
            field=models.EmailField(help_text='Emailadresse für automatische Updates und Nachfragen, wird nicht veröffentlicht', max_length=254),
        ),
        migrations.AlterField(
            model_name='unterantrag',
            name='kontaktperson',
            field=models.CharField(blank=True, help_text='Eine spezifische Kontaktperson für Nachfragen, wird nicht veröffentlicht', max_length=100),
        ),
    ]
