# Generated by Django 5.2.5 on 2025-08-12 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hauptverwalter', '0004_alter_sitzung_anfang'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitzung',
            options={'ordering': ['-legislatur__nummer', '-nummer']},
        ),
        migrations.AlterField(
            model_name='antrag',
            name='formell_eingereicht',
            field=models.DateTimeField(help_text='Formelles Einreichdatum für Priorisierung, Fristen etc'),
        ),
        migrations.AlterField(
            model_name='antrag',
            name='nummer',
            field=models.IntegerField(editable=False, help_text='Nummer des Antrags in der Legislatur', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='antrag',
            name='status',
            field=models.CharField(choices=[('B', 'In Beratung'), ('A', 'Angenommen'), ('N', 'Abgelehnt'), ('Z', 'Zurückgezogen'), ('X', 'Nicht behandelt')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='antrag',
            name='system_eingereicht',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='unterantrag',
            name='status',
            field=models.CharField(choices=[('B', 'In Beratung'), ('A', 'Angenommen'), ('N', 'Abgelehnt'), ('Z', 'Zurückgezogen'), ('X', 'Nicht behandelt')], max_length=1),
        ),
        migrations.AddConstraint(
            model_name='antrag',
            constraint=models.UniqueConstraint(fields=('legislatur', 'nummer'), name='unique_legislatur_nummer_antrag'),
        ),
    ]
