# Generated by Django 5.2.5 on 2026-01-19 17:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hauptverwalter', '0004_antrag_anmerkungen_extern_antrag_anmerkungen_intern_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOPname',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Der TOP-Name für alle Lesungen mit diesem Prio-Wert', max_length=200)),
                ('prio', models.IntegerField(help_text='Niedrige Werte tauchen auf generierten Tagesordnungen früher auf', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prioritätswert, der mit diesem Namen bezeichnet werden soll')),
                ('sitzung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hauptverwalter.sitzung')),
            ],
            options={
                'ordering': ['sitzung__nummer', 'prio'],
                'unique_together': {('name', 'sitzung'), ('prio', 'sitzung')},
            },
        ),
    ]
