# Generated by Django 5.2.5 on 2026-01-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hauptverwalter', '0005_topname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antrag',
            name='typ',
            field=models.CharField(choices=[('F', 'Finanzantrag'), ('S', 'Satzungs- oder Ordnungsänderungsantrag'), ('P', 'Positionierungsantrag'), ('B', 'Bericht / Diskussion'), ('A', 'Antrag')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='lesung',
            name='status',
            field=models.CharField(choices=[('AV', 'Softwarevorschlag'), ('NN', 'Noch nicht gelesen'), ('E', 'Erfolgreich gelesen'), ('V', 'Manuell Vertagt'), ('ZV', 'Wegen Ende der Sitzung vertagt'), ('B', 'Wegen Beschlussunfähigkeit vertagt'), ('A', 'Abgestimmt'), ('T', 'Schwebende Lesung / als Tischvorlage'), ('NT', 'Aufname nach §10 (5) GeschO')], default='NN', help_text='In Welchem Status ist die Lesung', max_length=2),
        ),
        migrations.AlterField(
            model_name='sitzung',
            name='ende',
            field=models.DateTimeField(blank=True, help_text='Wann endet(e) die Sitzung? (erst nach Sitzung eintragen, bitte)', null=True),
        ),
    ]
