# Generated by Django 5.2.5 on 2026-07-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hauptverwalter', '0005_alter_anhang_id_alter_faden_id_alter_lesung_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagesordnungspunkt',
            name='dringlichkeit_beantragt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='finanzantrag',
            name='antragssumme',
            field=models.DecimalField(decimal_places=2, help_text='In Euro', max_digits=20),
        ),
    ]
