# Generated by Django 5.2.5 on 2025-08-12 13:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hauptverwalter', '0005_alter_sitzung_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unterantrag',
            name='formell_eingereicht',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='unterantrag',
            name='hauptantrag',
            field=models.ForeignKey(editable=False, limit_choices_to={'status': 'B'}, on_delete=django.db.models.deletion.CASCADE, to='hauptverwalter.antrag'),
        ),
        migrations.AlterField(
            model_name='unterantrag',
            name='nummer',
            field=models.IntegerField(editable=False, help_text='Nummer des Subantrags', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='unterantrag',
            name='system_eingereicht',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddConstraint(
            model_name='unterantrag',
            constraint=models.UniqueConstraint(fields=('hauptantrag', 'nummer'), name='unique_hauptantrag_nummer_unterantrag'),
        ),
    ]
