# Generated by Django 5.2.5 on 2026-07-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hauptverwalter', '0006_tagesordnungspunkt_dringlichkeit_beantragt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitzung',
            name='anmerkungen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
