# Generated by Django 5.2.5 on 2025-08-12 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hauptverwalter', '0006_alter_unterantrag_formell_eingereicht_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unterantrag',
            name='hauptantrag',
            field=models.ForeignKey(limit_choices_to={'status': 'B'}, on_delete=django.db.models.deletion.CASCADE, to='hauptverwalter.antrag'),
        ),
    ]
