# Generated by Django 5.2.5 on 2026-01-24 21:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hauptverwalter', '0006_alter_antrag_typ_alter_lesung_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antrag',
            name='formell_eingereicht',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Formelles Einreichdatum für Priorisierung, Fristen etc'),
        ),
        migrations.AlterField(
            model_name='unterantrag',
            name='formell_eingereicht',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Formelles Einreichdatum für Priorisierung, Fristen etc'),
        ),
    ]
