# Generated by Django 5.2.5 on 2025-08-12 17:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hauptverwalter', '0007_alter_unterantrag_hauptantrag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unterantrag',
            options={'ordering': ['hauptantrag__legislatur__nummer', 'hauptantrag__nummer', 'nummer']},
        ),
        migrations.AlterField(
            model_name='unterantrag',
            name='status',
            field=models.CharField(choices=[('B', 'In Beratung'), ('A', 'Angenommen'), ('N', 'Abgelehnt'), ('Z', 'Zurückgezogen'), ('X', 'Nicht behandelt')], default='B', max_length=1),
        ),
        migrations.CreateModel(
            name='Lesung',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('protokolleintraege', models.TextField(blank=True, help_text='Protokolleinträge zur Lesung, z.B. Diskussionsnotizen, GO-Anträge', max_length=7000)),
                ('status', models.CharField(choices=[('NN', 'Noch nicht gelesen'), ('E', 'Erfolgreich gelesen'), ('V', 'Manuell Vertagt'), ('ZV', 'Wegen Ende der Sitzung vertagt'), ('B', 'Wegen Beschlussunfähigkeit vertagt'), ('A', 'Abgestimmt'), ('T', 'Schwebende Lesung / als Tischvorlage')], help_text='In Welchem Status ist die Lesung', max_length=2)),
                ('antrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hauptverwalter.antrag')),
                ('sitzung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hauptverwalter.sitzung')),
            ],
            options={
                'ordering': ['antrag__legislatur__nummer', 'antrag__nummer', 'sitzung__nummer'],
                'unique_together': {('antrag', 'sitzung')},
            },
        ),
    ]
