# Generated by Django 5.2.5 on 2026-01-27 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hauptverwalter', '0007_alter_antrag_formell_eingereicht_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitzung',
            name='anzeigen',
            field=models.BooleanField(blank=True, default=True, help_text='Soll die Sitzung der Öffentlichkeit auf Indexseiten angezeigt werden?', null=True),
        ),
        migrations.AddField(
            model_name='sitzung',
            name='protokollsitzung',
            field=models.ForeignKey(blank=True, help_text='Die Sitzung, in der das Protokoll beschlossen wurde', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hauptverwalter.sitzung'),
        ),
        migrations.AddField(
            model_name='sitzung',
            name='status',
            field=models.CharField(choices=[('N', 'Noch kein Protokoll'), ('V', 'Protokollvorschlag vorgelegt'), ('B', 'Protokoll beschlossen')], default='N', help_text='Status der Sitzung / des Protokolls', max_length=1),
        ),
    ]
