# Generated by Django 5.2.5 on 2026-07-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hauptverwalter', '0007_sitzung_anmerkungen'),
    ]

    operations = [
        migrations.AddField(
            model_name='soantrag',
            name='zu_aendernde_satzung',
            field=models.CharField(default='Beispielsatzung', max_length=300, verbose_name='Name der zu ändernden/einzurichtenden Satzung'),
            preserve_default=False,
        ),
    ]
