# Generated by Django 5.2.5 on 2026-07-13 17:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hauptverwalter', '0008_soantrag_zu_aendernde_satzung'),
    ]

    operations = [
        migrations.AddField(
            model_name='faden',
            name='eingereicht',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vorlage',
            name='geheim',
            field=models.BooleanField(default=False, help_text='Ist das hier die nichtöffentliche Version der Vorlage?'),
        ),
    ]
