# Generated by Django 5.2.5 on 2026-02-10 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hauptverwalter', '0008_sitzung_anzeigen_sitzung_protokollsitzung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='antrag',
            name='wants_updates',
            field=models.BooleanField(default=True, help_text='Möchte der Antragssteller Updates zu diesem Antrag erhalten?'),
        ),
        migrations.AddField(
            model_name='sitzung',
            name='datei',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Tagesordnung / Protokoll'),
        ),
        migrations.AddField(
            model_name='unterantrag',
            name='wants_updates',
            field=models.BooleanField(default=True, help_text='Möchte der Antragssteller Updates zu diesem Antrag erhalten?'),
        ),
        migrations.AlterField(
            model_name='antrag',
            name='minlesungen',
            field=models.IntegerField(blank=True, default=1, help_text='Minimal nötige Lesungen bis zur Abstimmung', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='sitzung',
            name='sondersitzung',
            field=models.BooleanField(blank=True, default=False, help_text='Ist die Sitzung eine Sondersitzung?'),
        ),
    ]
