# Generated by Django 5.2.5 on 2025-08-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hauptverwalter', '0008_alter_unterantrag_options_alter_unterantrag_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesung',
            name='abstimmbar',
            field=models.BooleanField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='lesung',
            name='dringlichkeit_beantragt',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesung',
            name='status',
            field=models.CharField(choices=[('AV', 'Softwarevorschlag'), ('NN', 'Noch nicht gelesen'), ('E', 'Erfolgreich gelesen'), ('V', 'Manuell Vertagt'), ('ZV', 'Wegen Ende der Sitzung vertagt'), ('B', 'Wegen Beschlussunfähigkeit vertagt'), ('A', 'Abgestimmt'), ('T', 'Schwebende Lesung / als Tischvorlage')], default='NN', help_text='In Welchem Status ist die Lesung', max_length=2),
        ),
    ]
