# Generated by Django 5.2.5 on 2026-02-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hauptverwalter', '0009_antrag_wants_updates_sitzung_datei_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antrag',
            name='wants_updates',
            field=models.BooleanField(blank=True, default=True, help_text='Möchte der Antragssteller Updates zu diesem Antrag erhalten?', null=True),
        ),
        migrations.AlterField(
            model_name='unterantrag',
            name='wants_updates',
            field=models.BooleanField(blank=True, default=True, help_text='Möchte der Antragssteller Updates zu diesem Antrag erhalten?', null=True),
        ),
    ]
