# Generated by Django 5.2.5 on 2025-08-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hauptverwalter', '0009_lesung_abstimmbar_lesung_dringlichkeit_beantragt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesung',
            name='abstimmbar',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='lesung',
            name='dringlichkeit_beantragt',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
