# Generated by Django 5.2.5 on 2025-08-13 14:45

import hauptverwalter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hauptverwalter', '0010_alter_lesung_abstimmbar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='antrag',
            name='anhang',
            field=models.FileField(blank=True, help_text='Anhang an den Antrag', null=True, upload_to=hauptverwalter.models.makeuploadpathanhang),
        ),
        migrations.AddField(
            model_name='antrag',
            name='haushaltsposten',
            field=models.CharField(blank=True, help_text='Aus welchem Haushaltsposten wird Geld beantragt (nur Kennummer)?', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='antrag',
            name='kontaktperson',
            field=models.CharField(blank=True, help_text='Eine spezifische Kontaktperson für Nachfragen', max_length=100),
        ),
        migrations.AddField(
            model_name='antrag',
            name='orgsatzungsaenderung',
            field=models.BooleanField(blank=True, default=False, help_text='Geht es um eine Änderung der Organisationssatzung?'),
        ),
        migrations.AddField(
            model_name='antrag',
            name='synopse',
            field=models.FileField(blank=True, help_text='Synopse bei Änderung von Ordnungen oder Satzungen', null=True, upload_to=hauptverwalter.models.makeuploadpatsynopse),
        ),
        migrations.AddField(
            model_name='antrag',
            name='typ',
            field=models.CharField(choices=[('F', 'Finanzantrag'), ('S', 'Satzungs- oder Ordnungsänderungsantrag'), ('P', 'Positionierungsantrag'), ('A', 'Antrag')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='unterantrag',
            name='anhang',
            field=models.FileField(blank=True, help_text='Anhang an den Änderungsantrag', null=True, upload_to=hauptverwalter.models.makeuploadpathanhang),
        ),
        migrations.AddField(
            model_name='unterantrag',
            name='kontaktperson',
            field=models.CharField(blank=True, help_text='Eine spezifische Kontaktperson für Nachfragen', max_length=100),
        ),
        migrations.AlterField(
            model_name='antrag',
            name='kontaktemail',
            field=models.EmailField(help_text='Emailadresse für automatische Updates und Nachfragen', max_length=254),
        ),
        migrations.AlterField(
            model_name='antrag',
            name='status',
            field=models.CharField(choices=[('B', 'In Beratung'), ('A', 'Angenommen'), ('N', 'Abgelehnt'), ('Z', 'Zurückgezogen'), ('X', 'Nicht behandelt'), ('P', 'Vom Präsidium zurückgewiesen')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='lesung',
            name='abstimmbar',
            field=models.BooleanField(blank=True, editable=False, help_text='Kann bei dieser Lesung planmäßig abgestimmt werden?', null=True),
        ),
        migrations.AlterField(
            model_name='lesung',
            name='dringlichkeit_beantragt',
            field=models.BooleanField(blank=True, default=False, help_text='Könnte in dieser Lesung abgestimmt werden, wenn ein Dringlichkeitsantrag angeommen wird?', null=True),
        ),
        migrations.AlterField(
            model_name='lesung',
            name='protokolleintraege',
            field=models.TextField(blank=True, help_text='Protokolleinträge zur Lesung, z.B. Diskussionsnotizen, GO-Anträge', max_length=50000),
        ),
        migrations.AlterField(
            model_name='unterantrag',
            name='kontaktemail',
            field=models.EmailField(help_text='Emailadresse für automatische Updates und Nachfragen', max_length=254),
        ),
        migrations.AlterField(
            model_name='unterantrag',
            name='status',
            field=models.CharField(choices=[('B', 'In Beratung'), ('A', 'Angenommen'), ('N', 'Abgelehnt'), ('Z', 'Zurückgezogen'), ('X', 'Nicht behandelt'), ('P', 'Vom Präsidium zurückgewiesen')], default='B', max_length=1),
        ),
    ]
