# Generated by Django 5.2.5 on 2025-08-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hauptverwalter', '0011_antrag_anhang_antrag_haushaltsposten_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesung',
            name='abstimmbar',
            field=models.BooleanField(blank=True, default=False, editable=False, help_text='Kann bei dieser Lesung planmäßig abgestimmt werden?', null=True),
        ),
    ]
